In [42]:
#importing required packages
import pandas as pd
import datetime as datetime

In [69]:
#reading as csv file using pandas
df=pd.read_csv('D:/Data Science/covid_test.csv')

In [5]:
#printing out first 100 records
df.head(100)

,Date,Country_Region,Province_State,Case_Type,Cases,Difference,Prep_Flow_Runtime,Latest_Date,Lat,Long
0,03-11-2020,US,Arizona,Recovered,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
1,03-11-2020,US,Arizona,Deaths,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
2,03-11-2020,US,Arizona,Confirmed,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
3,03-11-2020,US,Arizona,Active,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
4,2/15/2020,US,Arizona,Recovered,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.8162,-111.2845
...,...,...,...,...,...,...,...,...,...,...
95,2/25/2020,US,Arizona,Active,0,-1,3/21/2020 7:39:09 AM,3/20/2020,33.2918,-112.4291
96,1/24/2020,US,Arizona,Recovered,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
97,1/24/2020,US,Arizona,Deaths,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
98,1/24/2020,US,Arizona,Confirmed,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
99,1/24/2020,US,Arizona,Active,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661

In [70]:
#converting the datetime formmating which we have in raw data like 03-11-2020 & 2/25/2020
df['Date']=pd.to_datetime(df.Date)

In [7]:
#checking date has been changed as expected
df.head(100)

,Date,Country_Region,Province_State,Case_Type,Cases,Difference,Prep_Flow_Runtime,Latest_Date,Lat,Long
0,2020-03-11,US,Arizona,Recovered,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
1,2020-03-11,US,Arizona,Deaths,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
2,2020-03-11,US,Arizona,Confirmed,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
3,2020-03-11,US,Arizona,Active,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
4,2020-02-15,US,Arizona,Recovered,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.8162,-111.2845
...,...,...,...,...,...,...,...,...,...,...
95,2020-02-25,US,Arizona,Active,0,-1,3/21/2020 7:39:09 AM,3/20/2020,33.2918,-112.4291
96,2020-01-24,US,Arizona,Recovered,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
97,2020-01-24,US,Arizona,Deaths,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
98,2020-01-24,US,Arizona,Confirmed,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661
99,2020-01-24,US,Arizona,Active,0,0,3/21/2020 7:39:09 AM,3/20/2020,32.0575,-111.6661

In [9]:
df.Date.head(10)

0   2020-03-11
1   2020-03-11
2   2020-03-11
3   2020-03-11
4   2020-02-15
5   2020-02-15
6   2020-02-15
7   2020-02-15
8   2020-01-30
9   2020-01-30
Name: Date, dtype: datetime64[ns]

In [71]:
"""syntax to drop a non required cols.. axis =1 denotes Columns (which means in Y axis in terms in of graph view, axis =0 means
rows. you can assume as x axis in graph to remember easily)"""
df=df.drop(['Prep_Flow_Runtime','Latest_Date','Lat','Long'],axis=1)

In [46]:
#sorting the data by date
df=df.sort_values(by=['Date'])

In [66]:
#pivoting the dataframe as the column Case_Type has four values [Active Confirmed Deaths Recovered] need to tranform to columnar manner
import numpy as np
df2=pd.pivot_table(df,index=['Date','Country_Region','Province_State'],columns='Case_Type',values='Cases',aggfunc = np.sum)
#df2=df.pivot(columns=('Country_Region','Case_Type'),values='Cases')

In [62]:
#Oops the pivoting has been done !!!
df2.head(100)

Case_Type                                               Active  Confirmed  \
Date       Country_Region Province_State
2020-01-23 Australia      Australian Capital Territory     0.0        0.0
                          New South Wales                  0.0        0.0
                          Northern Territory               0.0        0.0
                          Queensland                       0.0        0.0
                          South Australia                  0.0        0.0
...                                                        ...        ...
           US             Missouri                         0.0        0.0
                          Montana                          0.0        0.0
                          Nebraska                         0.0        0.0
                          Nevada                           0.0        0.0
                          New Hampshire                    0.0        0.0

Case_Type                                               Deaths  Recovered
Date       Country_Region Province_State
2020-01-23 Australia      Australian Capital Territory     0.0        0.0
                          New South Wales                  0.0        0.0
                          Northern Territory               0.0        0.0
                          Queensland                       0.0        0.0
                          South Australia                  0.0        0.0
...                                                        ...        ...
           US             Missouri                         0.0        0.0
                          Montana                          0.0        0.0
                          Nebraska                         0.0        0.0
                          Nevada                           0.0        0.0
                          New Hampshire                    0.0        0.0

[100 rows x 4 columns]

In [64]:
#writing the output to csv file
df2.to_csv('D:/Data Science/covid_py2.csv')

In [67]:
#if you need query a dataframe using its index column, need to use dfname.query()
df2.query(("Date==2020-01-23") and ("Province_State=='Washington'"))

Case_Type                                 Active  Confirmed  Deaths  Recovered
Date       Country_Region Province_State
2020-01-23 US             Washington           1          1       0          0
2020-01-24 US             Washington           1          1       0          0
2020-01-25 US             Washington           1          1       0          0
2020-01-26 US             Washington           1          1       0          0
2020-01-27 US             Washington           1          1       0          0
2020-01-28 US             Washington           1          1       0          0
2020-01-29 US             Washington           1          1       0          0
2020-01-30 US             Washington           1          1       0          0
2020-01-31 US             Washington           1          1       0          0
2020-02-01 US             Washington           1          1       0          0
2020-02-02 US             Washington           1          1       0          0
2020-02-03 US             Washington           1          1       0          0
2020-02-04 US             Washington           1          1       0          0
2020-02-05 US             Washington           1          1       0          0
2020-02-06 US             Washington           1          1       0          0
2020-02-07 US             Washington           1          1       0          0
2020-02-08 US             Washington           1          1       0          0
2020-02-09 US             Washington           0          1       0          1
2020-02-10 US             Washington           0          1       0          1
2020-02-11 US             Washington           0          1       0          1
2020-02-12 US             Washington           0          1       0          1
2020-02-13 US             Washington           0          1       0          1
2020-02-14 US             Washington           0          1       0          1
2020-02-15 US             Washington           0          1       0          1
2020-02-16 US             Washington           0          1       0          1
2020-02-17 US             Washington           0          1       0          1
2020-02-18 US             Washington           0          1       0          1
2020-02-19 US             Washington           0          1       0          1
2020-02-20 US             Washington           0          1       0          1
2020-02-21 US             Washington           0          1       0          1
2020-02-22 US             Washington           0          1       0          1
2020-02-23 US             Washington           0          1       0          1
2020-02-24 US             Washington           0          1       0          1
2020-02-25 US             Washington           0          1       0          1
2020-02-26 US             Washington           0          1       0          1
2020-02-27 US             Washington           0          1       0          1
2020-02-28 US             Washington           0          1       0          1
2020-02-29 US             Washington           5          7       1          1
2020-03-01 US             Washington           9         11       1          1
2020-03-02 US             Washington          11         18       6          1
2020-03-03 US             Washington          19         27       7          1
2020-03-04 US             Washington          28         39      10          1
2020-03-05 US             Washington          58         70      11          1
2020-03-06 US             Washington          64         78      13          1
2020-03-07 US             Washington          85        102      16          1
2020-03-08 US             Washington         103        122      18          1
2020-03-09 US             Washington         102        122      19          1
2020-03-10 US             Washington         243        267      23          1
2020-03-11 US             Washington         336        366      29          1
2020-03-12 US             Washington         410        442      31          1
2020-03-13 US             Washington         530        568      37          1
2020-03-14 US             Washington         534        572      37          1
2020-03-15 US             Washington         602        643      40          1
2020-03-16 US             Washington         855        904      48          1
2020-03-17 US             Washington        1020       1076      55          1
2020-03-18 US             Washington         959       1014      55          0
2020-03-19 US             Washington        1302       1376      74          0
2020-03-20 US             Washington        1441       1524      83          0

In [33]:
#df2[(df2.Date=='2020-01-23') & (df2.Province_State=='Washington')]
#df2[df2.Province_State=='Washington']
df2.query(("Date==2020-01-23") and ("Province_State=='Washington'"))

,,Case_Type,Active,Confirmed,Deaths,Recovered
Date,Country_Region,Province_State,,,,
2020-01-23,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-24,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-25,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-26,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-27,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-28,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-29,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-30,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-01-31,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-01,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-02,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-03,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-04,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-05,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-06,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-07,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-08,US,Washington,0.076923,0.076923,0.000000,0.000000
2020-02-09,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-10,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-11,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-12,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-13,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-14,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-15,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-16,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-17,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-18,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-19,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-20,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-21,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-22,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-23,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-24,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-25,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-26,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-27,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-28,US,Washington,0.000000,0.076923,0.000000,0.076923
2020-02-29,US,Washington,0.384615,0.538462,0.076923,0.076923
2020-03-01,US,Washington,0.692308,0.846154,0.076923,0.076923
2020-03-02,US,Washington,0.846154,1.384615,0.461538,0.076923
2020-03-03,US,Washington,1.461538,2.076923,0.538462,0.076923
2020-03-04,US,Washington,2.153846,3.000000,0.769231,0.076923
2020-03-05,US,Washington,4.461538,5.384615,0.846154,0.076923
2020-03-06,US,Washington,4.923077,6.000000,1.000000,0.076923
2020-03-07,US,Washington,6.538462,7.846154,1.230769,0.076923
2020-03-08,US,Washington,7.923077,9.384615,1.384615,0.076923
2020-03-09,US,Washington,7.846154,9.384615,1.461538,0.076923
2020-03-10,US,Washington,18.692308,20.538462,1.769231,0.076923
2020-03-11,US,Washington,25.846154,28.153846,2.230769,0.076923
2020-03-12,US,Washington,31.538462,34.000000,2.384615,0.076923
2020-03-13,US,Washington,40.769231,43.692308,2.846154,0.076923
2020-03-14,US,Washington,41.076923,44.000000,2.846154,0.076923
2020-03-15,US,Washington,46.307692,49.461538,3.076923,0.076923
2020-03-16,US,Washington,65.769231,69.538462,3.692308,0.076923
2020-03-17,US,Washington,78.461538,82.769231,4.230769,0.076923
2020-03-18,US,Washington,73.769231,78.000000,4.230769,0.000000
2020-03-19,US,Washington,100.153846,105.846154,5.692308,0.000000
2020-03-20,US,Washington,110.846154,117.230769,6.384615,0.000000

Please ignore the trail cells as it just for my reference

In [34]:
df[df['Province_State']=='Washington']

            Date Country_Region Province_State  Case_Type  Cases  Difference
41800 2020-01-23             US     Washington  Recovered      0           0
41801 2020-01-23             US     Washington     Deaths      0           0
41802 2020-01-23             US     Washington  Confirmed      1           0
41803 2020-01-23             US     Washington     Active      1           0
40909 2020-01-23             US     Washington     Deaths      0           0
...          ...            ...            ...        ...    ...         ...
42723 2020-03-20             US     Washington     Active      0           0
52135 2020-03-20             US     Washington     Active   1441         139
52134 2020-03-20             US     Washington  Confirmed   1524         148
52133 2020-03-20             US     Washington     Deaths     83           9
52132 2020-03-20             US     Washington  Recovered      0           0

[3016 rows x 6 columns]

In [35]:
pd_list=[["mani",2],["venkat",3],["mani",4],["mani",5],["venkat",5]]

In [37]:
dff=pd.DataFrame(pd_list,columns=['name','performance'])
dff.head()

     name  performance
0    mani            2
1  venkat            3
2    mani            4
3    mani            5
4  venkat            5

In [41]:
dff.pivot(columns='name',values='performance').head()

name  mani  venkat
0      2.0     NaN
1      NaN     3.0
2      4.0     NaN
3      5.0     NaN
4      NaN     5.0