In [ ]:
from pathlib import Path
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
import numpy as np
# ^^^ pyforest auto-imports - don't write above this line

In [2]:
ds=pd.read_csv('D:\\Data_Science\\Machine_Learning\\KNN\\adult.csv')
ds.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,#NAME?,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
age               5000 non-null object
workclass         5000 non-null object
fnlwgt            5000 non-null object
education         5000 non-null object
education_num     5000 non-null object
marital_status    5000 non-null object
occupation        5000 non-null object
relationship      5000 non-null object
race              5000 non-null object
sex               5000 non-null object
capital_gain      5000 non-null int64
capital_loss      5000 non-null int64
hours_per_week    5000 non-null int64
native_country    5000 non-null object
income            5000 non-null object
dtypes: int64(3), object(12)
memory usage: 586.1+ KB

In [4]:
ds.dtypes

age               object
workclass         object
fnlwgt            object
education         object
education_num     object
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [5]:
ds.describe()

       capital_gain  capital_loss  hours_per_week
count   5000.000000   5000.000000     5000.000000
mean    1033.640200     93.696800       40.519000
std     7051.802077    410.801418       12.109193
min        0.000000      0.000000        1.000000
25%        0.000000      0.000000       40.000000
50%        0.000000      0.000000       40.000000
75%        0.000000      0.000000       45.000000
max    99999.000000   2547.000000       99.000000

In [6]:
ds.workclass.value_counts()

Private             3435
Self-emp-not-inc     383
?                    331
Local-gov            329
State-gov            193
Self-emp-inc         182
Federal-gov          146
Without-pay            1
Name: workclass, dtype: int64

In [8]:
ds.education_num.value_counts()

9         1597
10        1114
13         819
14         251
11         215
7          198
12         163
6          144
4           98
15          88
5           74
#NAME?      57
16          55
8           55
3           43
2           22
1            7
Name: education_num, dtype: int64

In [9]:
ds.marital_status.value_counts()

Married-civ-spouse       2270
Never-married            1659
Divorced                  682
Widowed                   160
Separated                 158
Married-spouse-absent      66
Married-AF-spouse           5
Name: marital_status, dtype: int64

In [10]:
ds.occupation.value_counts()

Prof-specialty       625
Craft-repair         619
Exec-managerial      618
Sales                588
Adm-clerical         576
Other-service        495
?                    331
Machine-op-inspct    312
Transport-moving     247
Handlers-cleaners    196
Farming-fishing      143
Tech-support         140
Protective-serv       90
Priv-house-serv       18
Armed-Forces           2
Name: occupation, dtype: int64

In [11]:
ds.race.value_counts()

White                 4021
Black                  493
#NAME?                 264
Asian-Pac-Islander     145
Amer-Indian-Eskimo      48
Other                   29
Name: race, dtype: int64

In [12]:
ds.sex.value_counts()

Male      3332
Female    1621
#NAME?      47
Name: sex, dtype: int64

In [14]:
ds.native_country.value_counts()

United-States                 4465
Mexico                         104
?                               97
Canada                          28
Germany                         22
Philippines                     22
El-Salvador                     16
Puerto-Rico                     16
England                         16
China                           15
Jamaica                         15
Cuba                            14
Dominican-Republic              13
India                           12
Italy                           12
Iran                            11
Vietnam                         10
Guatemala                       10
Taiwan                          10
Japan                            9
South                            9
Poland                           9
Portugal                         7
Haiti                            6
Greece                           6
Columbia                         5
Nicaragua                        5
Ecuador                          4
Ireland                          4
Cambodia                         4
Trinadad&Tobago                  4
Outlying-US(Guam-USVI-etc)       3
Honduras                         3
Peru                             3
France                           3
Thailand                         2
Yugoslavia                       2
Laos                             2
Hong                             1
Scotland                         1
Name: native_country, dtype: int64

In [21]:
ds_ed=ds.drop('education',axis=1)
ds_ed.loc[(ds_ed.age=='#NAME?'),'age'] = np.nan
ds_ed.loc[(ds_ed.workclass=='?'),'workclass'] = np.nan
ds_ed.loc[(ds_ed.education_num=='#NAME?'),'education_num'] = np.nan
ds_ed.loc[(ds_ed.occupation=='?'),'occupation'] = np.nan
ds_ed.loc[(ds_ed.education_num=='?'),'education_num'] = np.nan
ds_ed.loc[(ds_ed.race=='#NAME?'),'race'] = np.nan

ds_ed.loc[(ds_ed.sex=='#NAME?'),'sex'] = np.nan
ds_ed.loc[(ds_ed.native_country=='?'),'native_country'] = np.nan
ds_ed.loc[(ds_ed.fnlwgt=='#NAME?'),'fnlwgt'] = np.nan

In [22]:
ds_ed['age'] = ds_ed['age'].fillna(ds_ed['age'].mode()[0])
ds_ed['workclass'] = ds_ed['workclass'].fillna(ds_ed['workclass'].mode()[0])
ds_ed['education_num'] = ds_ed['education_num'].fillna(ds_ed['education_num'].mode()[0])
ds_ed['occupation'] = ds_ed['occupation'].fillna(ds_ed['occupation'].mode()[0])
ds_ed['education_num'] = ds_ed['education_num'].fillna(ds_ed['education_num'].mode()[0])
ds_ed['race'] = ds_ed['race'].fillna(ds_ed['race'].mode()[0])

ds_ed['sex'] = ds_ed['sex'].fillna(ds_ed['sex'].mode()[0])
ds_ed['native_country'] = ds_ed['native_country'].fillna(ds_ed['native_country'].mode()[0])
ds_ed['fnlwgt'] = ds_ed['fnlwgt'].fillna(ds_ed['fnlwgt'].mode()[0])

In [18]:
ds_ed.head(20)

,age,workclass,fnlwgt,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>50K
15,34,Private,245487,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,31,Self-emp-not-inc,#NAME?,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K

In [24]:
ds_ed.age=ds_ed.age.astype('int64')
ds_ed.fnlwgt=ds_ed.fnlwgt.astype('int64')
ds_ed.education_num=ds_ed.education_num.astype('int64')

In [25]:
ds_ed.dtypes

age                int64
workclass         object
fnlwgt             int64
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [29]:
#ds_ed[('income'=='<=50K')]['income_target']=0
ds_ed['income_target']=np.where(ds_ed['income']=='<=50K',0,1)

ds_ed
#df['rating'] = np.where(df['line_race']==0, 0, df['rating'])

,age,workclass,fnlwgt,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,income_target
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,0
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,0
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,0
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43,Private,222971,3,Never-married,Machine-op-inspct,Unmarried,White,Female,0,0,40,Mexico,<=50K,0
4996,31,Private,259425,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K,1
4997,47,Self-emp-inc,212120,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,>50K,1
4998,31,Private,245880,9,Never-married,Adm-clerical,Not-in-family,White,Male,0,0,60,United-States,<=50K,0
4999,58,Local-gov,54947,10,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,55,United-States,<=50K,0

In [35]:
ds_cat=ds_ed[['workclass','marital_status','occupation','relationship','race','sex','native_country']]
ds_no=ds_ed[['age','fnlwgt','education_num','capital_gain','capital_loss','hours_per_week']]
y=ds_ed['income_target']

In [36]:
df_cat_dum=pd.get_dummies(ds_cat,drop_first=True)

In [37]:
df_cat_dum

,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Without-pay,marital_status_Married-AF-spouse,marital_status_Married-civ-spouse,marital_status_Married-spouse-absent,marital_status_Never-married,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,0,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4996,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4997,0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4998,0,1,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
4999,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0

In [41]:
X=pd.concat([ds_no,df_cat_dum],axis=1)
X

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week,workclass_Local-gov,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,77516,13,2174,0,40,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,50,83311,13,0,0,13,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2,38,215646,9,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
3,53,234721,7,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4,28,338409,13,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,43,222971,3,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4996,31,259425,9,0,0,40,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4997,47,212120,9,0,0,40,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
4998,31,245880,9,0,0,60,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
4999,58,54947,10,0,0,55,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [42]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4995    0
4996    1
4997    1
4998    0
4999    0
Name: income_target, Length: 5000, dtype: int32

In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [54]:
X_scale

array([[ 0.03593442, -1.05821935,  1.16204955, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [ 0.84859611, -1.00347843,  1.16204955, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [-0.03794391,  0.24658891, -0.42328408, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       ...,
       [ 0.6269611 ,  0.21328149, -0.42328408, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [-0.55509226,  0.53218634, -0.42328408, ...,  0.30985565,
        -0.04476615, -0.020004  ],
       [ 1.43962278, -1.2714114 , -0.02695067, ...,  0.30985565,
        -0.04476615, -0.020004  ]])

In [50]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
X_scale=scx.fit_transform(X)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X_scale, y, test_size=0.25, random_state=82)

In [55]:
log=LogisticRegression()
log.fit(X_train,y_train)

D:\Anaconda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [56]:
logis_y_pred=log.predict(X_test)

In [67]:
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,roc_auc_score,classification_report

In [68]:
print("logistics accuracy",accuracy_score(y_test,logis_y_pred))
print("roc_curve ",roc_auc_score(y_test,logis_y_pred))
print("confusion matrix",confusion_matrix(y_test,logis_y_pred))

logistics accuracy 0.8352
roc_curve  0.7473274620582696
confusion matrix [[868  76]
 [130 176]]

In [70]:
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [71]:
dt_y_pred=dt.predict(X_test)


print("Decision accuracy",accuracy_score(y_test,dt_y_pred))
print("roc_curve ",roc_auc_score(y_test,dt_y_pred))
print("confusion matrix",confusion_matrix(y_test,dt_y_pred))

Decision accuracy 0.7984
roc_curve  0.7251717071009196
confusion matrix [[820 124]
 [128 178]]

In [73]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf_y_pred=dt.predict(X_test)


print("Rf Base accuracy",accuracy_score(y_test,rf_y_pred))
print("roc_curve ",roc_auc_score(y_test,rf_y_pred))
print("confusion matrix",confusion_matrix(y_test,rf_y_pred))

Rf Base accuracy 0.7984
roc_curve  0.7251717071009196
confusion matrix [[820 124]
 [128 178]]

D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

In [75]:
from sklearn.model_selection import GridSearchCV
params={'n_estimators':[200,500,700,800],'max_depth':[10,15,18,20],'min_samples_leaf':[3,6,9]}
gscv=GridSearchCV(rf,params,verbose=3)

In [76]:
gscv.fit(X_train,y_train)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

Fitting 3 folds for each of 48 candidates, totalling 144 fits
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.851, total=   0.3s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.842, total=   0.3s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=200 ..............

[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s

[CV]  max_depth=10, min_samples_leaf=3, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.854, total=   0.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.846, total=   0.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=500, score=0.846, total=   0.7s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.855, total=   1.1s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.844, total=   1.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=700, score=0.847, total=   1.0s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.855, total=   1.2s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.845, total=   1.2s
[CV] max_depth=10, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=3, n_estimators=800, score=0.846, total=   1.2s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.853, total=   0.3s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.843, total=   0.3s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=200, score=0.843, total=   0.3s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.855, total=   0.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.842, total=   0.8s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=500, score=0.844, total=   0.7s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.852, total=   1.0s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.842, total=   1.0s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=700, score=0.846, total=   1.0s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.853, total=   1.1s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.842, total=   1.2s
[CV] max_depth=10, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=6, n_estimators=800, score=0.846, total=   1.3s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.838, total=   0.3s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=200, score=0.842, total=   0.3s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.847, total=   0.7s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.838, total=   0.7s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=500, score=0.846, total=   0.7s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.847, total=   1.0s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.837, total=   1.0s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=700, score=0.841, total=   1.0s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.848, total=   1.2s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.839, total=   1.1s
[CV] max_depth=10, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=10, min_samples_leaf=9, n_estimators=800, score=0.846, total=   1.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.848, total=   0.3s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.842, total=   0.3s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.852, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.844, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=500, score=0.850, total=   0.8s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.854, total=   1.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.846, total=   1.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=700, score=0.848, total=   1.1s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.852, total=   1.3s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.846, total=   1.3s
[CV] max_depth=15, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=3, n_estimators=800, score=0.849, total=   1.3s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.853, total=   0.3s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.841, total=   0.3s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=200, score=0.846, total=   0.3s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.852, total=   0.7s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.842, total=   0.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=500, score=0.846, total=   0.8s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.853, total=   1.1s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............

[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.843, total=   1.0s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=700, score=0.851, total=   1.1s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.850, total=   1.2s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.843, total=   1.2s
[CV] max_depth=15, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=6, n_estimators=800, score=0.849, total=   1.2s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.848, total=   0.3s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.839, total=   0.3s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=200, score=0.844, total=   0.3s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.851, total=   0.7s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.838, total=   0.7s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=500, score=0.849, total=   0.7s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.852, total=   1.0s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.840, total=   1.0s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=700, score=0.841, total=   1.0s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.852, total=   1.1s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.839, total=   1.1s
[CV] max_depth=15, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=15, min_samples_leaf=9, n_estimators=800, score=0.846, total=   1.2s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.844, total=   0.4s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=200, score=0.847, total=   0.3s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.850, total=   0.8s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.846, total=   0.8s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=500, score=0.850, total=   0.8s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.850, total=   1.2s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.848, total=   1.1s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=700, score=0.850, total=   1.2s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.851, total=   1.3s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.845, total=   1.3s
[CV] max_depth=18, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=3, n_estimators=800, score=0.851, total=   1.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.846, total=   0.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.839, total=   0.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.851, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.840, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=500, score=0.849, total=   0.8s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.851, total=   1.1s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.844, total=   1.1s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=700, score=0.848, total=   1.1s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.850, total=   1.2s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.843, total=   1.2s
[CV] max_depth=18, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=6, n_estimators=800, score=0.850, total=   1.2s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.848, total=   0.3s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.838, total=   0.3s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=200, score=0.851, total=   0.3s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.848, total=   0.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.841, total=   0.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=500, score=0.846, total=   0.7s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.854, total=   1.0s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.841, total=   1.0s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=700, score=0.846, total=   1.0s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.850, total=   1.2s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.839, total=   1.1s
[CV] max_depth=18, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=18, min_samples_leaf=9, n_estimators=800, score=0.848, total=   1.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............

[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.844, total=   0.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=200, score=0.849, total=   0.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.850, total=   0.8s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.842, total=   0.8s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=500, score=0.850, total=   0.8s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.851, total=   1.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.845, total=   1.1s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=700, score=0.845, total=   1.2s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.850, total=   1.4s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.847, total=   1.3s
[CV] max_depth=20, min_samples_leaf=3, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=3, n_estimators=800, score=0.849, total=   1.3s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.851, total=   0.3s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.844, total=   0.3s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=200, score=0.850, total=   0.3s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.850, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.839, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=500, score=0.848, total=   0.8s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.851, total=   1.1s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.845, total=   1.1s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=700, score=0.849, total=   1.1s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.853, total=   1.2s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.841, total=   1.2s
[CV] max_depth=20, min_samples_leaf=6, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=6, n_estimators=800, score=0.849, total=   1.3s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.849, total=   0.3s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.840, total=   0.3s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=200 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=200, score=0.844, total=   0.3s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.850, total=   0.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.840, total=   0.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=500 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=500, score=0.849, total=   0.7s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.850, total=   1.1s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.840, total=   1.0s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=700 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=700, score=0.847, total=   1.1s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.850, total=   1.2s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.842, total=   1.3s
[CV] max_depth=20, min_samples_leaf=9, n_estimators=800 ..............
[CV]  max_depth=20, min_samples_leaf=9, n_estimators=800, score=0.843, total=   1.3s

[Parallel(n_jobs=1)]: Done 144 out of 144 | elapsed:  2.0min finished

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=10, n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'max_depth': [10, 15, 18, 20],
                         'min_samples_leaf': [3, 6, 9],
                         'n_estimators': [200, 500, 700, 800]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [77]:
gscv.best_score_

0.8490666666666666

In [78]:
gscv.best_params_

{'max_depth': 10, 'min_samples_leaf': 3, 'n_estimators': 500}

In [79]:
gscv.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [80]:
rf_improve=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [81]:
rf_improve.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=10, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=3, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [82]:
rf_improve.oob_score_

0.8488

In [84]:
imp_final_pred=rf_improve.predict(X_test)
print(accuracy_score(y_test,imp_final_pred))
print("Rf Imp accuracy",accuracy_score(y_test,imp_final_pred))
print("roc_curve ",roc_auc_score(y_test,imp_final_pred))
print("confusion matrix",confusion_matrix(y_test,imp_final_pred))

0.8544
Rf Imp accuracy 0.8544
roc_curve  0.7357441564196299
confusion matrix [[914  30]
 [152 154]]

In [85]:
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
knn_pred=knn.predict(X_test)

In [86]:
print("KNN accuracy",accuracy_score(y_test,knn_pred))
print("roc_curve ",roc_auc_score(y_test,knn_pred))
print("confusion matrix",confusion_matrix(y_test,knn_pred))

KNN accuracy 0.8048
roc_curve  0.717261410213803
confusion matrix [[839 105]
 [139 167]]